url: "https://leejae-h.github.io"
baseurl: ""
title: 개발is:e
markdown: kramdown

# for atom feed
author:
  name: Lee JaeHyung
  email: dlwogud725@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
